-- ============================================================
-- DISABLED — This migration referenced provider_profiles.verified
-- which does not exist. The document-verification gate will be
-- re-introduced properly in a future migration once the schema
-- has the required columns.
-- See 20260327400000 for the active policy fix.
-- ============================================================
-- no-op
